easy_admin:
  site_name: Conference Guestbook

  design:
    menu:
      - { route: 'homepage', label: 'Назад к сайту', icon: 'home' }
      - { entity: 'Conference', label: 'Конференции', icon: 'map-marker' }
      - { entity: 'Comment', label: 'Комментарии', icon: 'comments' }

  entities:
    Conference:
      class: App\Entity\Conference

    Comment:
      class: App\Entity\Comment
      list:
        fields:
          - { property: 'author', label: 'Автор', type: 'string' }
          - { property: 'email', label: 'Почта', type: 'email' }
          - { property: 'createdAt', label: 'СозданоВ', type: 'datetime' }
          - { property: 'conference', label: 'Конференция', type: 'string' }
        sort: ['createdAt', 'ASC']
        filters: ['conference']
      edit:
        fields:
          - { property: 'conference' }
          - { property: 'createdAt', type: datetime, type_options: { disabled: true } }
          - 'author'
          - { property: 'email', type: 'email' }
          - text